// CHAPTER 2 - c# LANGUAGE BASIC

// 4-1 NUMERIC TYPES
// 4-2 NUMERIC LITERALS
// 4-3 NUMERIC SUFFIXES
// 4-4 NUMERIC CONVERSIONS
// 4-5 INCREMENT AND DECREMENT OPERATORS
// 4-6 INTEGRAL DIVISION
// 4-7 INTEGRAL OVERFLOW
// 4-8 OVERFLOW CHECKING
// 4-9 OVERFLOW CHECKING WITH CONSTANT EXPRESSIONS
// 4-10 /- AND 16-BIT LITERALS
// 4-11 SPECIAL FLOAT AND DOUBLE VALUES
// 4-12 REAL ROUDING ERROS
